# Generated by Django 4.2.1 on 2023-06-13 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("nickname", models.CharField(blank=True, max_length=100, null=True)),
                ("house", models.CharField(blank=True, max_length=50, null=True)),
                ("sex", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "picture",
                    models.ImageField(blank=True, null=True, upload_to="pictures"),
                ),
                ("ballot_number", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "candidate",
            },
        ),
        migrations.CreateModel(
            name="Election",
            fields=[
                (
                    "election_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField()),
                ("type_of_election", models.CharField(max_length=55)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "election",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="voter_id",
            field=models.CharField(default="6632571", max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="votes_cast",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="management.candidate",
                    ),
                ),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="management.election",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "vote",
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sn", models.IntegerField(default=1)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="management.election",
                    ),
                ),
            ],
            options={
                "db_table": "position",
            },
        ),
        migrations.AddField(
            model_name="election",
            name="admin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="elections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="election",
            name="candidates",
            field=models.ManyToManyField(
                related_name="candidates", to="management.candidate"
            ),
        ),
        migrations.AddField(
            model_name="election",
            name="voters",
            field=models.ManyToManyField(
                related_name="voters", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="management.position",
            ),
        ),
    ]
