# Generated by Django 4.2.1 on 2023-06-13 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="election",
            name="candidates",
            field=models.ManyToManyField(
                blank=True, related_name="candidates", to="management.candidate"
            ),
        ),
        migrations.AlterField(
            model_name="election",
            name="voters",
            field=models.ManyToManyField(
                blank=True, related_name="voters", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
