# Generated by Django 4.2.1 on 2023-06-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "management",
            "0002_candidate_election_user_voter_id_user_votes_cast_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                default="422692@gmail.com", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="voter_id",
            field=models.CharField(
                blank=True, default="422692", max_length=10, unique=True
            ),
        ),
    ]
