# Generated by Django 4.2.1 on 2023-06-13 16:20

from django.db import migrations, models
import management.models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0006_alter_user_email_alter_user_voter_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                default=management.models.User.generate_default_email,
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="voter_id",
            field=models.CharField(
                blank=True,
                default=management.models.User.generate_voter_id,
                max_length=10,
                unique=True,
            ),
        ),
    ]
